apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-api-secrets
  labels:
    app: backend-api
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
