apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-api
  labels:
    app: backend-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6000
      protocol: TCP
      name: http
  selector:
    app: backend-api
    app.kubernetes.io/instance: {{ .Release.Name }}
