replicaCount: 2

image:
  repository: sifytul/backend-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6000

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

mysql:
  host: ""
  port: 3306
  user: app_user
  password: app_password
  database: app_db

redis:
  host: ""
  port: 6379
  password: redis_password

cacheTTL: 300
