apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-init
  labels:
    app: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  init.sql: |
{{ .Files.Get "files/init.sql" | indent 4 }}
