apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  user-password: {{ .Values.auth.password | b64enc | quote }}
