apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secrets
  labels:
    app: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc | quote }}
